name: test.client
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: check out action
        uses: actions/checkout@v3
      - run: |
          echo list of all folders and files
          ls -la
          cd src
          ls -la
      - name: node version setup
        uses: actions/setup-node@v3
        with: node-version:"16.x"
      - name: install node modules
        run: npm ci
      - name: build
        run: npm run build
      - name: check build folders
        run: ls -la
