name: test.client
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: check out action
        uses: actions/checkout@v3
      - run: |
          list of all folders
          ls -la
          cd src
          ls -la
