name: test.client
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: check out action
        uses: actions/checkout@v3
      - run: |
          ls -la
          cd src
          ls -la
      - name: node version setup
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: install node modules
        run: npm ci
      - name: build
        run: npm run build
      - name: check build folders
        run: ls -la
      - name: deploy
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        with:
          args: deploy --dir=client/build --prod
      - name: End
        run: echo "Project deployed successfully"
